title: AkrmEdm
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "AkrmEdm"
job: "〈Tinkerer〉"

phone_number: 7950533
address: HA. Uligan
email: akrmedm@egmail.com
linkedin_username: akrmedm
github_username: akrmedm
instagram_username: akrmedm
twitter_username: akrmedm
facebook_username: akrmedm
youtube_username: akrmedm
blog_url: https://akrmedm.github.io/

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag