subject: Trainings
listing-order: 4
icon: "/assets/img/flask.svg"
contents:
  - title: AutoCAD Basics for Beginners, Infinica Academy
    date: 06 November 2023 - 11 December 2023
  - title: C# Coding Bootcamp, Ilm Vidhaaraa
    date: 06 August 2023 - 07 September 2023
  - title: Internal Audit, CSTI
    date: 18 June 2023 - 22nd June 2023
  - title: Training in Field Administrations for Civil Servants of Maldives, NCGG
    date: 31 October 2022 - 11 November 2022 
  - title: NoCode Web Development using WordPress for Beginners, Javaabu Academy
    date: 10 October 2022 - 18 November 2022
  - title: Photoshop Masterclass Photo Manipulation, Javaabu Academy
    date: 07 October 2022 - 11 November 2022
  - title: Introduction To Photoshop and Illustrator, Javaabu Academy
    date: 23rd July 2022 - 26 August 2022
  - title: Social Media Marketing Masterclass, Javaabu Academy
    date: 10 June 2022 - 17 July 2022
  - title: Introduction to Motion Design and Animation, Javaabu Academy
    date: 13 May 2022 - 16 June 2022
  - title: JavaScript Dhaskuraanantha?, Javaabu Academy
    date: 12 March 2022 - 10 June 2022
  - title: Windows Server Basic, Twin Tutors
    date: 19 February 2022 - 21 April 2022
  - title: Laravel for Beginners, Javaabu Academy
    date: 19 January 2022 - 07 May 2022
  - title: NoCode Android Application Development & Monetization, Javaabu Academy
    date: 08 January 2022 - 28 February 2022
  - title: Dynamic CMS Development with PHP & MySQL, Javaabu Academy
    date: 12 October 2021 - 08 December 2021

